language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

services:
  - rabbitmq

before_script:
  - sudo apt-get install -y beanstalkd
  - sudo beanstalkd -l 127.0.0.1 -p 11300 &
  - composer require satooshi/php-coveralls:dev-master --dev --no-interaction --prefer-source
  - mkdir -p build/logs

script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then vendor/bin/phpunit --colors --coverage-clover build/logs/clover.xml; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "hhvm" ]]; then vendor/bin/phpunit --colors; fi

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then vendor/bin/coveralls -v; fi
