language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

services:
  - rabbitmq

before_script:
  - sudo apt-get install -y beanstalkd
  - sudo beanstalkd -l 127.0.0.1 -p 11300 &
  - composer require satooshi/php-coveralls:dev-master --dev --no-progress --prefer-source
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
